services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=la_roca_worship
      - POSTGRES_USER=emi
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data