### POST Login Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "emiperez@gmail.com",
    "password": "12345678"
}

### POST Login User

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "cintia@gmail.com",
    "password": "12345678"
}

### GET Profile

GET http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5N2Q1OTkyLTVlMGItNGEyNy1iMjllLTVlODVjNGU0ZGUwYiIsInVzZXJuYW1lIjoiY2ludGlhayIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzI5NTU3MzI4LCJleHAiOjE3Mjk1NTkxMjh9.vbshy0Oohf5PfxsomHqVM7zEgHSfdV3iWqiGEdXwzaI

### POST Register

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "cintiak",
    "firstName": "Cintia",
    "lastName": "Kromplewski",
    "email": "cintia@gmail.com",
    "password": "12345678"
}

### POST Register 2

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "emiperez",
    "firstName": "Emiliano",
    "lastName": "Perez",
    "email": "emiperez@gmail.com",
    "password": "12345678"
}