### GET Lists

GET http://localhost:5000/api/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg0ZjQ0MjNhLTA0OWUtNDY4Zi05YTI5LTQ3NGUxM2EwZWJhYiIsInVzZXJuYW1lIjoiY2ludGlhayIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzI5NzI1MzI2LCJleHAiOjE3Mjk3MjcxMjZ9.JDrYMLsnaYlRVbZHdZXz3abSHrSYdHdygmVLdHUBOtw

### GET List

GET http://localhost:5000/api/lists/256232c0-d285-49cc-9cce-900a965dbb37/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5N2Q1OTkyLTVlMGItNGEyNy1iMjllLTVlODVjNGU0ZGUwYiIsInVzZXJuYW1lIjoiY2ludGlhayIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzI5NTU5Mjg2LCJleHAiOjE3Mjk1NjEwODZ9.0i7heIJsFACmm8ICbXf8lYqCioWlznSOTSUWKdYPq5Y

### POST List

POST http://localhost:5000/api/lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5N2Q1OTkyLTVlMGItNGEyNy1iMjllLTVlODVjNGU0ZGUwYiIsInVzZXJuYW1lIjoiY2ludGlhayIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzI5NTU5Mjg2LCJleHAiOjE3Mjk1NjEwODZ9.0i7heIJsFACmm8ICbXf8lYqCioWlznSOTSUWKdYPq5Y

{
  "title": "Bautismo" 
}

### POST List Song

POST http://localhost:5000/api/lists/256232c0-d285-49cc-9cce-900a965dbb37/8eada754-08a8-4c8d-84f5-30750c4a3255
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5N2Q1OTkyLTVlMGItNGEyNy1iMjllLTVlODVjNGU0ZGUwYiIsInVzZXJuYW1lIjoiY2ludGlhayIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzI5NTU5Mjg2LCJleHAiOjE3Mjk1NjEwODZ9.0i7heIJsFACmm8ICbXf8lYqCioWlznSOTSUWKdYPq5Y


###


PATCH http://localhost:5000/api/lists/0ec1cbe2-35c2-4a71-a02d-6a270ef7aa1c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5N2Q1OTkyLTVlMGItNGEyNy1iMjllLTVlODVjNGU0ZGUwYiIsInVzZXJuYW1lIjoiY2ludGlhayIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzI5NTU3MzI4LCJleHAiOjE3Mjk1NTkxMjh9.vbshy0Oohf5PfxsomHqVM7zEgHSfdV3iWqiGEdXwzaI

{
  "title": "Bautismo Nuevo"
}

###

DELETE http://localhost:5000/api/lists/86272e48-dff4-44fa-b23b-66a7bd1e3d3b

###

GET http://localhost:5000/api/lists/test/listSong