### GET All Users 

GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2YTA1N2I3LTIzYWQtNDFmMy04NWJkLTFlM2RiYTA4YTU2ZiIsInVzZXJuYW1lIjoiZW1pcGVyZXoiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MzMzMjk1NDQsImV4cCI6MTczMzMzMTM0NH0.WKwNWvq-xnsK55iVZEP_go9WqkIQnXCjnH272P712i4

### GET User By Id

GET http://localhost:5000/api/users/0da46b78-5828-4656-9a16-40dcd8d0a24f

### POST User 1

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username": "cintiak",
    "firstName": "Cintia",
    "lastName": "Kromplewski",
    "email": "cintia@gmail.com",
    "password": "12345678"
}

### POST User 2

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username": "emiperez",
    "firstName": "Emiliano",
    "lastName": "Perez",
    "email": "emiperez@gmail.com",
    "password": "12345678"
}

### PATCH User

PATCH http://localhost:5000/api/users/03b78bc9-1a91-4a72-8227-e2533f2bbd74
Content-Type: application/json

{
    "username": "cintiak" 
}

### DELETE User

DELETE http://localhost:5000/api/users
Content-Type: application/json